---
# tasks file for nginx

- name: Template index.html-easter_egg to index.html on target
  template:
    src: index.html-easter_egg.j2
    dest: "{{ target_dir }}/index.html"
    mode: 0644
  tags:
    - deploy-app
- name: Install Unzip
  package:
    name: unzip
    state: latest
- name: Unarchive playbook stacker game
  unarchive:
    src: playbook_stacker.zip
    dest: "{{ target_dir }}"
    mode: 0755
  tags:
    - deploy-app
