---

- hosts: linux
  tasks:
    - name: Configure a MOTD (Message Of The Day)
      copy:
        content: "Welcome to {{ item }} Linux - Ansible Rocks\n"
        dest: /etc/motd
      with_items:
        - CentOS
        - Ubuntu
      when: ansible_distribution == item
      notify: MOTD changed
  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed
- hosts: linux
  tasks:
  - name: Creating user
    user:
      name: "{{ item }}"
    with_items:
      - james
      - hayley
      - lily
      - anwen
  - name: Deleting user
    user:
      name: "{{ item }}"
      state: absent
    with_items:
      - james
      - hayley
      - lily
      - anwen
  - name: Creating users with dicts
    user:
      name: "{{ item.key }}"
      comment: "{{ item.value.full_name }}"
    with_dict:
      james:
        full_name: James Spurin
      hayley:
        full_name: Hayley Spurin
      lily:
        full_name: Lily Spurin
      anwen:
        full_name: Anwen Spurin
  - name: Removing users with dicts
    user:
      name: "{{ item.key }}"
      comment: "{{ item.value.full_name }}"
      state: absent
    with_dict:
      james:
        full_name: James Spurin
      hayley:
        full_name: Hayley Spurin
      lily:
        full_name: Lily Spurin
      anwen:
        full_name: Anwen Spurin
  - name: Creating users with subelements
    user:
      name: "{{ item.1 }}"
      comment: "{{ item.1 | title }} {{ item.0.surname }}"
      password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits,punctuation') | password_hash('sha512') }}"
    with_subelements:
      -
        - surname: Spurin
          members:
            - james
            - hayley
            - lily
            - anwen
        - surname: Darlington
          members:
            - freya
        - surname: Jalba
          members:
            - ana
        - surname: Angne
          members:
            - abhishek
        - surname: Mahmood
          members:
            - sara
      - members
  - name: Creating user directories
    file:
      dest: "/home/{{ item.0 }}/{{ item.1 }}"
      owner: "{{ item.0 }}"
      group: "{{ item.0 }}"
      state: directory
    with_nested:
      - [ james, hayley, freya, lily, anwen, ana, abhishek, sara ]
      - [ photos, movies, documents ]
  - name: Creating user directories synchronized
    file:
      dest: "/home/{{ item.0 }}/{{ item.1 }}"
      owner: "{{ item.0 }}"
      group: "{{ item.0 }}"
      state: directory
    with_together:
      - [ james, hayley, freya, lily, anwen, ana, abhishek, sara ]
      - [ tech, psychology, acting, dancing, playing, japanese, coffee, music ]
  - name: Create authorized key
    authorized_key:
      user: james
      key: "{{ item }}"
    with_file:
      - /home/ansible/.ssh/id_rsa.pub
  - name: Create sequence directories
    file:
      dest: "{{ item }}"
      state: directory
      owner: "james"
      group: "james"
    with_sequence: start=0 end=100 stride=10 format=/home/james/sequence_%d
  - name: Create hex equence directories
    file:
      dest: "{{ item }}"
      state: directory
      owner: "james"
      group: "james"
    with_sequence: start=0 end=16 stride=1 format=/home/james/hex_sequence_%x
  - name: Create hex equence directories with count
    file:
      dest: "{{ item }}"
      state: directory
      owner: "james"
      group: "james"
    with_sequence: count=5 format=/home/james/count_sequence_%x
  - name: Create random directory
    file:
      dest: "/home/james/{{ item }}"
      state: directory
      owner: "james"
      group: "james"
    with_random_choice:
      - google
      - facebook
      - microsoft
      - apple
  - name: Run a script until we hit 10
    script: random.sh
    register: result
    retries: 100
    until: result.stdout.find("10") != -1
    delay: 1

...
