---

- hosts: linux
  tasks:
    - name: A block of modules being executed
      block:
        - name: Example 1
          debug:
            msg: Example 1
        - name: Example 2
          debug:
            msg: Example 2
        - name: Example 3
          debug:
            msg: Example 3
    - name: A second block of modules being executed
      block:
        - name: Example 1 CentOS only
          debug:
            msg: Example 1 CentOS only
          when: ansible_distribution == 'CentOS'
        - name: Example 2 Ubuntu only
          debug:
            msg: Example 2 Ubuntu only
          when: ansible_distribution == 'Ubuntu'
        - name: Example 3 with items
          debug:
            msg: "Example 3 with items - {{ item }}"
          with_items: [ 'x', 'y', 'z' ]
    - name: Install patch and python-dns
      block:
        - name: Install patch
          package:
            name: patch
        - name: Install python3-dnspython
          package:
            name: python3-dnspython
      rescue:
        - name: Rollback patch
          package:
            name: patch
            state: absent
        - name: Rollback python3-dnspython
          package:
            name: python3-dnspython
            state: absent
      always:
        - debug:
            msg: This will always run, regardless

...
