---

- hosts: ubuntu-c
  tasks:
    - name: Pull images
      docker_image:
        docker_host: tcp://docker:2375
        name: "{{ item }}"
        source: pull
      with_items:
        - "centos:8"
        - ubuntu
        - redis
        - nginx
        - wernight/funbox
    - name: Create an nginx container
      docker_container:
        docker_host: tcp://docker:2375
        name: containerwebserver
        image: nginx
        image_name_mismatch: recreate
        ports:
          - 80:80
        container_default_behavior: no_defaults
    - name: Create a customised index.html
      copy:
        dest: /shared/index.html
        mode: 0644
        content: |
          Customised page for nginxcustomised
    - name: Create a customized Dockerfile
      copy:
        dest: /shared/Dockerfile
        mode: 0644
        content: |
          FROM nginx
          COPY index.html /usr/share/nginx/html/index.html
    - name: Build a customized image
      docker_image:
        docker_host: tcp://docker:2375
        name: nginxcustomized:latest
        source: build
        build:
          path: /shared
          pull: yes
        state: present
        force_source: true
    - name: Create an nginxcustomized container
      docker_container:
        docker_host: tcp://docker:2375
        name: containerwebserver
        image: nginxcustomized:latest
        image_name_mismatch: recreate
        ports:
          - 80:80
        container_default_behavior: no_defaults
        recreate: yes
    - name: Pull python image
      docker_image:
        docker_host: tcp://docker:2375
        name: python:3.8.5
        source: pull
    - name: Create 3 python containers
      docker_container:
        docker_host: tcp://docker:2375
        name: "python{{ item }}"
        image: python:3.8.5
        container_default_behavior: no_defaults
        command: sleep infinity
      with_sequence: 1-3

- hosts: containers
  gather_facts: false
  tasks:
    - name: Ping containers
      ping:

# Cleanup
- hosts: ubuntu-c
  tasks:
    - name: Remove old containers
      docker_container:
        docker_host: tcp://docker:2375
        name: "{{ item }}"
        state: absent
        container_default_behavior: no_defaults
      with_items:
        - containerwebserver
        - python1
        - python2
        - python3
    - name: Remove images
      docker_image:
        docker_host: tcp://docker:2375
        name: "{{ item }}"
        state: absent
      with_items:
        - centos:8
        - ubuntu
        - redis
        - nginx
        - wernight/funbox
        - nginxcustomized
        - python:3.8.5
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /shared/Dockerfile
        - /shared/index.html

...
