---

# The minis in YAML indicates a list item. The playbook contains a list of plays, with each play being a dictionary
-
  # Hosts: where our play will run and options it will run with
  hosts: linux
  user: root
  # Vars: variables that will apply to the play, on all target systems
  vars:
    motd_centos: "Welcome to CentOS Linux - Ansible Rocks\n"
    motd_ubuntu: "Welcome to Ubuntu Linux - Ansible Rocks\n"
  # Tasks: the list of tasks that will be executed within the play, this section can also be use for pre- and post-tasks
  tasks:
    - name: Configure the MOTD (Message Of The Day)
      copy:
        # src: centos_motd
        # content: Welcome to CentOS Linux - Ansible Rocks
        content: "{{ motd_centos }}"
        dest: /etc/motd
      notify: MOTD changed
      when:
        - ansible_distribution == "CentOS"
    - name: Configure the MOTD (Message Of The Day)
      copy:
        # src: centos_motd
        # content: Welcome to CentOS Linux - Ansible Rocks
        content: "{{ motd_ubuntu }}"
        dest: /etc/motd
      notify: MOTD changed
      when:
        - ansible_distribution == "Ubuntu"
  # Handlers: the list of handlers that are executed as a notify key from a task
  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD has been changed
  # Roles: list of roles to be imported into the play
...
