---

- hosts: centos1
  tasks:
    - name: Loop through list
      debug:
        msg: "An item: {{ item }}"
      with_items:
        - 3
        - 2
        - 1
        - Z
        - A
        - M
    - name: Loop through list, sorted
      debug:
        msg: "An item: {{ item }}"
      with_sorted_items:
        - 3
        - 2
        - 1
        - Z
        - A
        - M
- hosts: all
  tasks:
    - name: Reverse and upper ansible_distribution
      debug:
        msg: "Reverse and upper of ansible_distribution: {{ ansible_distribution | reverse_upper }}"

...
