---

- hosts: ubuntu3,centos3
  tasks:
    - name: Set a fact
      set_fact:
        our_fact: Ansible Rocks!
        ansible_distribution: "{{ ansible_distribution | upper }}"
    - name: Show custom fact
      debug:
        msg: "{{ our_fact }}"
    - name: Show ansible_distribution
      debug:
        msg: "{{ ansible_distribution }}"
    - name: Set our installation variables for CentOS
      set_fact:
        webserver_application_port: 80
        webserver_application_path: /usr/share/nginx/html
        webserver_application_user: root
      when: ansible_distribution == 'CENTOS'
    - name: Set our installation variables for Ubuntu
      set_fact:
        webserver_application_port: 8080
        webserver_application_path: /var/www/html
        webserver_application_user: nginx
      when: ansible_distribution == 'UBUNTU'
    - name: Show pre-set distribution-based facts
      debug:
        msg: "webserver_application_port: {{ webserver_application_port }} - webserver_application_path: {{ webserver_application_path }} - webserver_application_user: {{ webserver_application_user }}"
    - name: Pause our playbook for 2 seconds
      pause:
        seconds: 2
    - name: Prompt user to verify before continue
      pause:
        prompt: Please check that the webserver is running, press Enter to continue
    - name: Wait for a webserver to be running on port 80
      wait_for:
        port: 80

- hosts: ubuntu-c
  tasks:
    - name: Assemble conf.d to sshd_config
      assemble:
        src: conf.d
        dest: /tmp/sshd_config
    - name: Add centos1 to adhoc_group
      add_host:
        name: centos1
        groups: adhoc_group1, adhoc_group2

- hosts: adhoc_group1
  tasks:
    - name: Ping all in adhoc_group1
      ping:

- hosts: all
  tasks:
    - name: Create group based on ansible_distribution
      group_by:
        key: "custom_{{ ansible_distribution | lower }}"

- hosts: custom_centos
  tasks:
    - name: Ping all in custom_centos
      ping:

- hosts: centos
  tasks:
    - name: Fetch /etc/redhat-release
      fetch:
        src: /etc/redhat-release
        dest: /tmp/redhat-release
...
